version: '3.4'

services:
  yessir-interface:
    container_name: yessir-interface
    image: docker.io/brunovitalino/yessir-interface-image:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4200:80
