version: '3.4'

services:
  yessir-interface:
    container_name: yessir-interface
    image: docker.io/brunovitalino/yessir-interface-image:latest
    ports:
      - 4200:80
    restart: unless-stopped
